{"name": "test_login_unsuccessful_wrong_password", "status": "passed", "attachments": [{"name": "log", "source": "9448c443-0989-49ec-b695-d82174dd836a-attachment.txt", "type": "text/plain"}], "start": 1712936111393, "stop": 1712936111945, "uuid": "a4ca720d-648b-4f7a-81d3-daeffed5ed9f", "historyId": "e239060817bf559c35dc7c4f393607c8", "testCaseId": "e239060817bf559c35dc7c4f393607c8", "fullName": "usuario_personalizado.tests.test_login.LoginTests#test_login_unsuccessful_wrong_password", "labels": [{"name": "parentSuite", "value": "usuario_personalizado.tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "LoginTests"}, {"name": "host", "value": "3f21cf6986de"}, {"name": "thread", "value": "25-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "usuario_personalizado.tests.test_login"}]}