{"name": "test_login_unsuccessful_wrong_password", "status": "passed", "attachments": [{"name": "log", "source": "3cf43aad-53ba-4006-81cd-a15517ae393d-attachment.txt", "type": "text/plain"}], "start": 1712934873014, "stop": 1712934873574, "uuid": "9afa6b80-cd37-47d6-8095-97c5f38ca6e3", "historyId": "e239060817bf559c35dc7c4f393607c8", "testCaseId": "e239060817bf559c35dc7c4f393607c8", "fullName": "usuario_personalizado.tests.test_login.LoginTests#test_login_unsuccessful_wrong_password", "labels": [{"name": "parentSuite", "value": "usuario_personalizado.tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "LoginTests"}, {"name": "host", "value": "667ad7f82e85"}, {"name": "thread", "value": "21-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "usuario_personalizado.tests.test_login"}]}