[31m[1mERROR   [0m personas.models:models.py:131 Error al enviar el correo: database table is locked: titulos
[31m[1mERROR   [0m personas.models:models.py:131 Error al enviar el correo: database table is locked: titulos
[33mWARNING [0m django.request:log.py:241 Bad Request: /personas/titulos/
[33mWARNING [0m django.request:log.py:241 Bad Request: /personas/titulos/
[33mWARNING [0m django.request:log.py:241 Bad Request: /personas/titulos/