{"name": "test_login_unsuccessful_wrong_password", "status": "passed", "attachments": [{"name": "log", "source": "5c88d9a8-ba1a-4695-bce0-e311d44b8a03-attachment.txt", "type": "text/plain"}], "start": 1712934387757, "stop": 1712934388301, "uuid": "24528912-2caa-4233-bf6c-b43271536006", "historyId": "e239060817bf559c35dc7c4f393607c8", "testCaseId": "e239060817bf559c35dc7c4f393607c8", "fullName": "usuario_personalizado.tests.test_login.LoginTests#test_login_unsuccessful_wrong_password", "labels": [{"name": "parentSuite", "value": "usuario_personalizado.tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "LoginTests"}, {"name": "host", "value": "a12d9a0c5251"}, {"name": "thread", "value": "21-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "usuario_personalizado.tests.test_login"}]}